import type { OvertimePolicy } from '@/pages/Overtime/overtimePolicyTypes';

/** Seed rows for Overtime Policies UI (mock). */
export function seedOvertimePolicies(): OvertimePolicy[] {
    return [
        {
            id: 1,
            code: 'OT-WD',
            name: 'Weekday overtime',
            context: 'ordinary_weekday',
            rateMultiplier: 1.25,
            dailyThresholdHours: 8,
            dailyCapHours: 4,
            weeklyCapHours: 24,
            requiresApproval: true,
            minimumLeadTimeHours: 24,
            isActive: true,
            notes: 'Applies to hours worked beyond the standard 8h day on regular working days.',
        },
        {
            id: 2,
            code: 'OT-RD',
            name: 'Rest day overtime',
            context: 'rest_day',
            rateMultiplier: 1.3,
            dailyThresholdHours: 0,
            dailyCapHours: null,
            weeklyCapHours: null,
            requiresApproval: true,
            minimumLeadTimeHours: 48,
            isActive: true,
            notes: 'All hours on a scheduled rest day are premium; threshold at 0 for full-day coverage (mock).',
        },
        {
            id: 3,
            code: 'OT-RH',
            name: 'Regular holiday work',
            context: 'regular_holiday',
            rateMultiplier: 2,
            dailyThresholdHours: 0,
            dailyCapHours: null,
            weeklyCapHours: null,
            requiresApproval: true,
            minimumLeadTimeHours: null,
            isActive: true,
            notes: 'Double rate for work on regular national holidays (illustrative).',
        },
        {
            id: 4,
            code: 'OT-SH',
            name: 'Special holiday work',
            context: 'special_holiday',
            rateMultiplier: 1.3,
            dailyThresholdHours: 0,
            dailyCapHours: null,
            weeklyCapHours: null,
            requiresApproval: true,
            minimumLeadTimeHours: 24,
            isActive: true,
            notes: 'Special non-working day premium; verify against current labor code.',
        },
        {
            id: 5,
            code: 'OT-LEG',
            name: 'Legacy night differential (inactive)',
            context: 'ordinary_weekday',
            rateMultiplier: 1.1,
            dailyThresholdHours: 8,
            dailyCapHours: 8,
            weeklyCapHours: 16,
            requiresApproval: false,
            minimumLeadTimeHours: null,
            isActive: false,
            notes: 'Superseded by night-shift template — kept for reference only.',
        },
    ];
}
