import type { HrisDemoDirectoryFields } from '@/lib/hrisDemoDirectoryFields';
import { hrisAugmentTeamHrRowWithDemoDirectory } from '@/lib/hrisDemoDirectoryFields';
import type { TeamOvertimeRow } from '@/pages/Overtime/teamOvertimeTypes';

type TeamOvertimeRowBare = Omit<TeamOvertimeRow, keyof HrisDemoDirectoryFields>;

/** Sample rows for Employee Overtime team table (mock). */
export function seedTeamOvertimeRows(): TeamOvertimeRow[] {
    const base: TeamOvertimeRowBare[] = [
        {
            id: 201,
            employee: {
                display_name: 'Ana Morales',
                id_number: 'PMPC-10492',
                avatar_url: null,
            },
            unit_filter_value: 'u-panabo',
            unit_name: 'Panabo Branch',
            unit_code: 'PNB',
            ot_date: '2026-05-10',
            hours: 3,
            context: 'ordinary_weekday',
            policy_code: 'OT-WD',
            rate_multiplier: 1.25,
            status: 'approved',
            submitted_at: '2026-05-10',
            decided_at: '2026-05-11',
            approver_employee_id: null,
            approver_id_number: 'PMPC-20001',
            approver_name: 'R. Santos',
            reason: 'Cutover support.',
        },
        {
            id: 202,
            employee: {
                display_name: 'Jordan Cruz',
                id_number: 'PMPC-10177',
                avatar_url: null,
            },
            unit_filter_value: 'u-tagum',
            unit_name: 'Tagum Branch',
            unit_code: 'TAG',
            ot_date: '2026-05-04',
            hours: 6,
            context: 'rest_day',
            policy_code: 'OT-RD',
            rate_multiplier: 1.3,
            status: 'approved',
            submitted_at: '2026-05-04',
            decided_at: '2026-05-05',
            approver_employee_id: null,
            approver_id_number: 'PMPC-HRMO',
            approver_name: 'HR (mock)',
            reason: 'Inventory weekend.',
        },
        {
            id: 203,
            employee: {
                display_name: 'Mira Fernandez',
                id_number: 'PMPC-10801',
                avatar_url: null,
            },
            unit_filter_value: 'u-section-a',
            unit_name: 'Panabo — Section A',
            unit_code: 'PNB-A',
            ot_date: '2026-05-01',
            hours: 8,
            context: 'regular_holiday',
            policy_code: 'OT-RH',
            rate_multiplier: 2,
            status: 'approved',
            submitted_at: '2026-04-28',
            decided_at: '2026-04-29',
            approver_employee_id: null,
            approver_id_number: 'PMPC-HRCC',
            approver_name: 'HR Committee',
            reason: 'Holiday staffing.',
        },
        {
            id: 204,
            employee: {
                display_name: 'Leo Villarin',
                id_number: 'PMPC-10002',
                avatar_url: null,
            },
            unit_filter_value: 'u-hq',
            unit_name: 'Head Office',
            unit_code: 'HQ',
            ot_date: '2026-05-12',
            hours: 2.5,
            context: 'ordinary_weekday',
            policy_code: 'OT-WD',
            rate_multiplier: 1.25,
            status: 'rejected',
            submitted_at: '2026-05-12',
            decided_at: '2026-05-13',
            approver_employee_id: null,
            approver_id_number: 'PMPC-20002',
            approver_name: 'D. Ramos',
            reason: 'Same-day filing — policy requires 24h lead (mock).',
        },
        {
            id: 205,
            employee: {
                display_name: 'Sofia Delgado',
                id_number: 'PMPC-11220',
                avatar_url: null,
            },
            unit_filter_value: 'u-panabo',
            unit_name: 'Panabo Branch',
            unit_code: 'PNB',
            ot_date: '2026-05-18',
            hours: 4,
            context: 'special_holiday',
            policy_code: 'OT-SH',
            rate_multiplier: 1.3,
            status: 'approved',
            submitted_at: '2026-05-17',
            decided_at: '2026-05-17',
            approver_employee_id: null,
            approver_id_number: 'PMPC-HRMO',
            approver_name: 'HR (mock)',
            reason: 'Special non-working day coverage.',
        },
        {
            id: 206,
            employee: {
                display_name: 'Ethan Navarro',
                id_number: 'PMPC-11544',
                avatar_url: null,
            },
            unit_filter_value: 'u-tagum',
            unit_name: 'Tagum Branch',
            unit_code: 'TAG',
            ot_date: '2026-05-22',
            hours: 5,
            context: 'ordinary_weekday',
            policy_code: 'OT-WD',
            rate_multiplier: 1.25,
            status: 'rejected',
            submitted_at: '2026-05-22',
            decided_at: '2026-05-22',
            approver_employee_id: null,
            approver_id_number: 'PMPC-HRMO',
            approver_name: 'HR (mock)',
            reason: 'Shift ended early — hours not credited.',
        },
        {
            id: 207,
            employee: {
                display_name: 'Paulo Reyes',
                id_number: 'PMPC-10331',
                avatar_url: null,
            },
            unit_filter_value: 'u-panabo',
            unit_name: 'Panabo Branch',
            unit_code: 'PNB',
            ot_date: '2026-05-09',
            hours: 10,
            context: 'rest_day',
            policy_code: 'OT-RD',
            rate_multiplier: 1.3,
            status: 'approved',
            submitted_at: '2026-05-08',
            decided_at: '2026-05-08',
            approver_employee_id: null,
            approver_id_number: 'PMPC-20001',
            approver_name: 'R. Santos',
            reason: 'Overnight span — hours credited to rest day (mock).',
        },
        {
            id: 208,
            employee: {
                display_name: 'Ina Salvacion',
                id_number: 'PMPC-11998',
                avatar_url: null,
            },
            unit_filter_value: 'u-section-a',
            unit_name: 'Panabo — Section A',
            unit_code: 'PNB-A',
            ot_date: '2026-05-28',
            hours: 1.5,
            context: 'ordinary_weekday',
            policy_code: 'OT-WD',
            rate_multiplier: 1.25,
            status: 'approved',
            submitted_at: '2026-05-28',
            decided_at: '2026-05-29',
            approver_employee_id: null,
            approver_id_number: 'PMPC-20001',
            approver_name: 'R. Santos',
            reason: null,
        },
        {
            id: 209,
            employee: {
                display_name: 'Carlos Mendoza',
                id_number: 'PMPC-10765',
                avatar_url: null,
            },
            unit_filter_value: 'u-hq',
            unit_name: 'Head Office',
            unit_code: 'HQ',
            ot_date: '2026-05-30',
            hours: 7,
            context: 'special_holiday',
            policy_code: 'OT-SH',
            rate_multiplier: 1.3,
            status: 'approved',
            submitted_at: '2026-05-29',
            decided_at: '2026-05-29',
            approver_employee_id: null,
            approver_id_number: 'PMPC-HRMO',
            approver_name: 'HR (mock)',
            reason: 'Election special holiday staffing.',
        },
        {
            id: 210,
            employee: {
                display_name: 'Bea Lagman',
                id_number: 'PMPC-12001',
                avatar_url: null,
            },
            unit_filter_value: 'u-tagum',
            unit_name: 'Tagum Branch',
            unit_code: 'TAG',
            ot_date: '2026-05-14',
            hours: 2,
            context: 'ordinary_weekday',
            policy_code: 'OT-WD',
            rate_multiplier: 1.25,
            status: 'approved',
            submitted_at: '2026-05-14',
            decided_at: '2026-05-15',
            approver_employee_id: null,
            approver_id_number: 'PMPC-20002',
            approver_name: 'D. Ramos',
            reason: 'Training overrun.',
        },
    ];

    return base.map(hrisAugmentTeamHrRowWithDemoDirectory);
}
