import type { LeavePolicy } from '@/pages/Leave/leavePolicyTypes';

/** Seed rows for Leave Policies UI (mock). */
export function seedLeavePolicies(): LeavePolicy[] {
    return [
        {
            id: 1,
            code: 'VL',
            name: 'Vacation leave',
            unit: 'days',
            annualEntitlement: 15,
            useAccrual: true,
            accrualCadence: 'monthly',
            accrualPerPeriod: 1.25,
            maxBalance: 45,
            carryoverAllowed: true,
            carryoverCap: 30,
            paid: true,
            requiresApproval: true,
            appliesAfterMonths: null,
            isActive: true,
            notes: 'Accrues monthly; excess above cap forfeited at year-end unless carried over within cap.',
        },
        {
            id: 2,
            code: 'SL',
            name: 'Sick leave',
            unit: 'days',
            annualEntitlement: 12,
            useAccrual: false,
            accrualCadence: null,
            accrualPerPeriod: null,
            maxBalance: 90,
            carryoverAllowed: true,
            carryoverCap: null,
            paid: true,
            requiresApproval: false,
            appliesAfterMonths: null,
            isActive: true,
            notes: 'Granted annually on hire anniversary; medical certificate may be required per branch rules.',
        },
        {
            id: 3,
            code: 'PL',
            name: 'Parental leave',
            unit: 'days',
            annualEntitlement: 105,
            useAccrual: false,
            accrualCadence: null,
            accrualPerPeriod: null,
            maxBalance: null,
            carryoverAllowed: false,
            carryoverCap: null,
            paid: true,
            requiresApproval: true,
            appliesAfterMonths: null,
            isActive: true,
            notes: 'Statutory parental leave window; coordinate with HR before filing.',
        },
        {
            id: 4,
            code: 'LWOP',
            name: 'Leave without pay',
            unit: 'days',
            annualEntitlement: 0,
            useAccrual: false,
            accrualCadence: null,
            accrualPerPeriod: null,
            maxBalance: null,
            carryoverAllowed: false,
            carryoverCap: null,
            paid: false,
            requiresApproval: true,
            appliesAfterMonths: 6,
            isActive: true,
            notes: 'Discretionary unpaid absence; manager approval required.',
        },
        {
            id: 5,
            code: 'BL',
            name: 'Bereavement leave',
            unit: 'days',
            annualEntitlement: 5,
            useAccrual: false,
            accrualCadence: null,
            accrualPerPeriod: null,
            maxBalance: null,
            carryoverAllowed: false,
            carryoverCap: null,
            paid: true,
            requiresApproval: true,
            appliesAfterMonths: null,
            isActive: false,
            notes: 'Inactive template — pending policy review.',
        },
    ];
}
