import type { HrisDemoDirectoryFields } from '@/lib/hrisDemoDirectoryFields';
import { hrisAugmentTeamHrRowWithDemoDirectory } from '@/lib/hrisDemoDirectoryFields';
import type { TeamLeaveRow } from '@/pages/Leave/teamLeaveTypes';

type TeamLeaveRowBare = Omit<TeamLeaveRow, keyof HrisDemoDirectoryFields>;

/** Sample rows for Employee Leaves team table (mock). */
export function seedTeamLeaveRows(): TeamLeaveRow[] {
    const base: TeamLeaveRowBare[] = [
        {
            id: 101,
            employee: {
                display_name: 'Ana Morales',
                id_number: 'PMPC-10492',
                avatar_url: null,
            },
            unit_filter_value: 'u-panabo',
            unit_name: 'Panabo Branch',
            unit_code: 'PNB',
            leave_type_code: 'VL',
            leave_type_name: 'Vacation leave',
            start_date: '2026-05-12',
            end_date: '2026-05-14',
            is_half_day_start: false,
            is_half_day_end: false,
            duration_label: '3 days',
            status: 'approved',
            submitted_at: '2026-04-28',
            decided_at: '2026-04-29',
            approver_employee_id: null,
            approver_id_number: 'PMPC-20001',
            approver_name: 'R. Santos',
            reason: 'Family travel.',
        },
        {
            id: 102,
            employee: {
                display_name: 'Jordan Cruz',
                id_number: 'PMPC-10177',
                avatar_url: null,
            },
            unit_filter_value: 'u-tagum',
            unit_name: 'Tagum Branch',
            unit_code: 'TAG',
            leave_type_code: 'SL',
            leave_type_name: 'Sick leave',
            start_date: '2026-05-05',
            end_date: '2026-05-06',
            is_half_day_start: true,
            is_half_day_end: false,
            duration_label: '1.5 days',
            status: 'approved',
            submitted_at: '2026-05-04',
            decided_at: '2026-05-05',
            approver_employee_id: null,
            approver_id_number: 'PMPC-HRMO',
            approver_name: 'HR (mock)',
            reason: 'Medical appointment + recovery.',
        },
        {
            id: 103,
            employee: {
                display_name: 'Mira Fernandez',
                id_number: 'PMPC-10801',
                avatar_url: null,
            },
            unit_filter_value: 'u-section-a',
            unit_name: 'Panabo — Section A',
            unit_code: 'PNB-A',
            leave_type_code: 'VL',
            leave_type_name: 'Vacation leave',
            start_date: '2026-05-20',
            end_date: '2026-05-27',
            is_half_day_start: false,
            is_half_day_end: false,
            duration_label: '6 days',
            status: 'approved',
            submitted_at: '2026-05-01',
            decided_at: '2026-05-02',
            approver_employee_id: null,
            approver_id_number: 'PMPC-HRMO',
            approver_name: 'HR (mock)',
            reason: 'Long weekend extension.',
        },
        {
            id: 104,
            employee: {
                display_name: 'Leo Villarin',
                id_number: 'PMPC-10002',
                avatar_url: null,
            },
            unit_filter_value: 'u-hq',
            unit_name: 'Head Office',
            unit_code: 'HQ',
            leave_type_code: 'LWOP',
            leave_type_name: 'Leave without pay',
            start_date: '2026-05-18',
            end_date: '2026-05-19',
            is_half_day_start: false,
            is_half_day_end: false,
            duration_label: '2 days',
            status: 'rejected',
            submitted_at: '2026-05-02',
            decided_at: '2026-05-03',
            approver_employee_id: null,
            approver_id_number: 'PMPC-20002',
            approver_name: 'D. Ramos',
            reason: 'Personal errands.',
        },
        {
            id: 105,
            employee: {
                display_name: 'Sofia Delgado',
                id_number: 'PMPC-11220',
                avatar_url: null,
            },
            unit_filter_value: 'u-panabo',
            unit_name: 'Panabo Branch',
            unit_code: 'PNB',
            leave_type_code: 'BL',
            leave_type_name: 'Bereavement leave',
            start_date: '2026-05-08',
            end_date: '2026-05-10',
            is_half_day_start: false,
            is_half_day_end: false,
            duration_label: '3 days',
            status: 'approved',
            submitted_at: '2026-05-07',
            decided_at: '2026-05-07',
            approver_employee_id: null,
            approver_id_number: 'PMPC-20001',
            approver_name: 'R. Santos',
            reason: null,
        },
        {
            id: 106,
            employee: {
                display_name: 'Ethan Navarro',
                id_number: 'PMPC-11544',
                avatar_url: null,
            },
            unit_filter_value: 'u-tagum',
            unit_name: 'Tagum Branch',
            unit_code: 'TAG',
            leave_type_code: 'SL',
            leave_type_name: 'Sick leave',
            start_date: '2026-05-26',
            end_date: '2026-05-26',
            is_half_day_start: true,
            is_half_day_end: true,
            duration_label: '½ day',
            status: 'rejected',
            submitted_at: '2026-05-25',
            decided_at: '2026-05-25',
            approver_employee_id: null,
            approver_id_number: 'PMPC-HRMO',
            approver_name: 'HR (mock)',
            reason: 'Returned to work same day — record voided.',
        },
        {
            id: 107,
            employee: {
                display_name: 'Paulo Reyes',
                id_number: 'PMPC-10331',
                avatar_url: null,
            },
            unit_filter_value: 'u-panabo',
            unit_name: 'Panabo Branch',
            unit_code: 'PNB',
            leave_type_code: 'PL',
            leave_type_name: 'Parental leave',
            start_date: '2026-06-01',
            end_date: '2026-06-30',
            is_half_day_start: false,
            is_half_day_end: false,
            duration_label: '22 days',
            status: 'approved',
            submitted_at: '2026-04-15',
            decided_at: '2026-04-18',
            approver_employee_id: null,
            approver_id_number: 'PMPC-HRCC',
            approver_name: 'HR Committee',
            reason: 'Parental leave filing — docs on file.',
        },
        {
            id: 108,
            employee: {
                display_name: 'Ina Salvacion',
                id_number: 'PMPC-11998',
                avatar_url: null,
            },
            unit_filter_value: 'u-section-a',
            unit_name: 'Panabo — Section A',
            unit_code: 'PNB-A',
            leave_type_code: 'VL',
            leave_type_name: 'Vacation leave',
            start_date: '2026-05-03',
            end_date: '2026-05-04',
            is_half_day_start: false,
            is_half_day_end: false,
            duration_label: '2 days',
            status: 'approved',
            submitted_at: '2026-04-20',
            decided_at: '2026-04-21',
            approver_employee_id: null,
            approver_id_number: 'PMPC-20001',
            approver_name: 'R. Santos',
            reason: 'Conference travel overlap.',
        },
        {
            id: 109,
            employee: {
                display_name: 'Carlos Mendoza',
                id_number: 'PMPC-10765',
                avatar_url: null,
            },
            unit_filter_value: 'u-hq',
            unit_name: 'Head Office',
            unit_code: 'HQ',
            leave_type_code: 'VL',
            leave_type_name: 'Vacation leave',
            start_date: '2026-05-30',
            end_date: '2026-06-02',
            is_half_day_start: false,
            is_half_day_end: false,
            duration_label: '4 days',
            status: 'approved',
            submitted_at: '2026-05-28',
            decided_at: '2026-05-29',
            approver_employee_id: null,
            approver_id_number: 'PMPC-HRMO',
            approver_name: 'HR (mock)',
            reason: 'Holiday weekend trip.',
        },
        {
            id: 110,
            employee: {
                display_name: 'Bea Lagman',
                id_number: 'PMPC-12001',
                avatar_url: null,
            },
            unit_filter_value: 'u-tagum',
            unit_name: 'Tagum Branch',
            unit_code: 'TAG',
            leave_type_code: 'SL',
            leave_type_name: 'Sick leave',
            start_date: '2026-05-15',
            end_date: '2026-05-17',
            duration_label: '3 days',
            is_half_day_start: false,
            is_half_day_end: false,
            status: 'approved',
            submitted_at: '2026-05-14',
            decided_at: '2026-05-14',
            approver_employee_id: null,
            approver_id_number: 'PMPC-20002',
            approver_name: 'D. Ramos',
            reason: 'Flu — MC attached (mock).',
        },
    ];

    return base.map(hrisAugmentTeamHrRowWithDemoDirectory);
}
